# Generated by Django 4.1.7 on 2023-03-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_task_period_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='task_id',
            new_name='task',
        ),
    ]
