# Generated by Django 4.1.7 on 2023-04-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_task_id_period_task'),
        ('task', '0003_rename_task_id_period_task'),
    ]

    operations = [
    ]
